export const TOURS = [
  {
    id: 'all-colors',
    num: 'No. 01',
    region: 'Bishkek · Issyk-Kul',
    title_en: ['All colors', { italic: ' of Kyrgyzstan' }],
    title_ru: ['Все краски', { italic: ' Кыргызстана' }],
    sub_en: 'Все краски Кыргызстана',
    sub_ru: 'All colors of Kyrgyzstan',
    deck_en: 'Six days from Bishkek along Issyk-Kul: Burana Tower on the old Silk Road, Skazka canyon\'s red sandstone, an eagle-hunter demo, Jeti-Ögüz red rocks, horseback to Maiden\'s Tears falls, a lake cruise and a merino felt-weaving masterclass.',
    deck_ru: 'Шесть дней из Бишкека вдоль Иссык-Куля: Башня Бурана на древнем Шёлковом пути, красный песчаник каньона Сказка, демонстрация беркут-охоты, скалы Джеты-Огуз, конная прогулка к водопаду Девичьи слёзы, круиз по озеру и мастер-класс по войлоку из шерсти мериноса.',
    deck: 'Six days from Bishkek along Issyk-Kul: Burana Tower on the old Silk Road, Skazka canyon\'s red sandstone, an eagle-hunter demo, Jeti-Ögüz red rocks, horseback to Maiden\'s Tears falls, a lake cruise and a merino felt-weaving masterclass.',
    tag: 'Overview',
    tag_en: 'Overview',
    tag_ru: 'Обзорный',
    duration_en: '6 days',
    duration_ru: '6 дней',
    season_en: 'Jun — Oct',
    season_ru: 'Июн — Окт',
    altitude_en: '2800 m',
    altitude_ru: '2800 м',
    from_en: '80 000 ₽',
    from_ru: '80 000 ₽',
    region_en: 'Bishkek · Issyk-Kul',
    region_ru: 'Бишкек · Иссык-Куль',
    duration: '6 days',
    season: 'Jun — Oct',
    altitude: '2800 m',
    from: '80 000 ₽',
    photo_url: 'https://resize.tripster.ru/pBT7jZBEuwJ_KPlHz1F2bBTOKpY=/fit-in/1200x1000/filters:no_upscale()/https://cdn.tripster.ru/photos/034e0127-f246-48aa-adcd-09b5a5a0456c.jpg',
    photo_alt: 'Issyk-Kul shore at sunrise',
    photo: 'PHOTO — Issyk-Kul shore, mountains behind',
    pull_en: ['"You measure Kyrgyzstan in ', { mark: 'lake colors, not kilometers' }, '."'],
    pull_ru: ['«Кыргызстан измеряется ', { mark: 'красками озера, а не километрами' }, '.»'],
    attrib_en: '— Galya, team coordinator · Tripster rating 4.9',
    attrib_ru: '— Галя, координатор команды · рейтинг 4.9 на Трипстере',
    itin_en: [
      ['D01', 'Bishkek: transfer, Ala-Too square, welcome dinner'],
      ['D02', 'Burana Tower, lunch in Balykchy, eagle-hunter show, Skazka canyon, yurt camp by Issyk-Kul'],
      ['D03', 'Borskoon gorge, Champagne Splash falls, Jeti-Ögüz red rocks, horse trek to Maiden\'s Tears, Karakol'],
      ['D04', 'Grigorievka gorge, trout farm, Cholpon-Ata, boat cruise on Issyk-Kul, hot springs'],
      ['D05', 'Drive to Bishkek, merino felt-weaving masterclass, farewell dinner'],
      ['D06', 'Osh bazaar morning, transfer to airport at 13:00'],
    ],
    itin_ru: [
      ['Д01', 'Бишкек: трансфер, площадь Ала-Тоо, приветственный ужин'],
      ['Д02', 'Башня Бурана, обед в Балыкчи, беркут-шоу, каньон Сказка, юрточный лагерь у Иссык-Куля'],
      ['Д03', 'Ущелье Борскоон, водопад Брызги Шампанского, скалы Джеты-Огуз, конная прогулка к Девичьим слезам, Каракол'],
      ['Д04', 'Григорьевское ущелье, форелевое хозяйство, Чолпон-Ата, круиз по Иссык-Кулю, горячие источники'],
      ['Д05', 'Переезд в Бишкек, мастер-класс по войлоку из шерсти мериноса, прощальный ужин'],
      ['Д06', 'Ошский рынок утром, трансфер в аэропорт в 13:00'],
    ],
  },
];

export const FILTERS = [
  { id: 'all', label_en: 'All journeys', label_ru: 'Все маршруты' },
  { id: 'Overview', label_en: 'Overview', label_ru: 'Обзорные' },
];

export const GUIDES = [
  {
    en: 'Galya',
    ru: 'Галя',
    role: 'Team coordinator · Bishkek',
    p_en: 'Loves Kyrgyzstan and Turkey, hosts the All Colors of Kyrgyzstan team. Tripster rating 4.9, 535 travelers, two years on the platform.',
    p_ru: 'Любит Кыргызстан и Турцию, ведёт команду тура «Все краски Кыргызстана». Рейтинг 4.9 на Трипстере, 535 путешественников, два года на платформе.',
    photo_url: 'https://resize.tripster.ru/zujw-Ez-yXSSmxCOXRT5Kdc2PIM=/150x150/filters:no_upscale()/https://cdn.tripster.ru/avatars/68308bc7-621f-45d3-aeb9-6daa5b1d04d0.jpg',
    photo: 'PHOTO — Galya, team coordinator',
  },
  {
    en: 'Local driver',
    ru: 'Местный водитель',
    role: 'Sprinter · road captain',
    p_en: 'Drives the Sprinter minibus the whole route — Bishkek to Karakol and back. Knows every viewpoint, every detour, every place to stop for fresh trout.',
    p_ru: 'Ведёт микроавтобус Sprinter весь маршрут — от Бишкека до Каракола и обратно. Знает каждую смотровую, каждый объезд и места с лучшей форелью.',
    photo_url: 'https://resize.tripster.ru/q3Tca4RpxJszPcHP5se1BymDZpw=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/6e1dc0ba-578b-4a6c-8bc7-8cd870997748.jpg',
    photo: 'PHOTO — Sprinter on the Issyk-Kul road',
  },
  {
    en: 'Berkutchi host',
    ru: 'Беркутчи',
    role: 'Eagle hunter · Issyk-Kul',
    p_en: 'Hereditary eagle hunter from the south shore. Runs the demo on Day 2 — the bird, the lure, the call back to the glove. Twenty-plus years on the saddle.',
    p_ru: 'Потомственный беркутчи с южного берега Иссык-Куля. Ведёт демонстрацию на второй день — птица, приманка, возврат на руку. Больше двадцати лет в седле.',
    photo_url: 'https://resize.tripster.ru/y6PceUcGha-YchSFatTMqLd8NBw=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/c946e1ee-2574-45d0-8ea2-d51ac01d8588.jpg',
    photo: 'PHOTO — Berkutchi with golden eagle',
  },
  {
    en: 'Felt master',
    ru: 'Мастерица войлока',
    role: 'Merino weaving · Day 5',
    p_en: 'One of the senior women in the regional felt cooperative. Hosts the Day 5 masterclass — merino wool, traditional patterns, hands-on shyrdak.',
    p_ru: 'Одна из старших мастериц регионального войлочного кооператива. Ведёт мастер-класс пятого дня — шерсть мериноса, традиционные узоры, шырдак своими руками.',
    photo_url: 'https://resize.tripster.ru/BSFm7kis87lgSjzMGdV-ER5tbJk=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/ff10d249-b010-499b-bfad-d188da015480.jpg',
    photo: 'PHOTO — Felt master at the loom',
  },
];

export const PILLARS = [
  { n: 'I', en_h: 'We pay guides by the day, not the head.', ru_h: 'Гидам платим по дням, а не по людям.', en_p: 'Our lead guides earn a predictable salary across the season, so a rainy day doesn\'t cost them anything. Tips go straight to the host households.', ru_p: 'Ведущие гиды получают зарплату за сезон, а чаевые идут напрямую принимающим семьям.' },
  { n: 'II', en_h: 'Groups are capped at fourteen.', ru_h: 'Группа не больше четырнадцати.', en_p: 'A Sprinter seats fourteen comfortably and a yurt camp can host the same. Past that, the family ends up eating separately — which we refuse.', ru_p: 'В Sprinter удобно помещаются четырнадцать, столько же — в юрточном лагере. Больше — и семья ест отдельно, а это не наш формат.' },
  { n: 'III', en_h: 'Every itinerary has a rest moment.', ru_h: 'В каждом маршруте есть передышка.', en_p: 'Not a bonus hike. A real pause — hot springs on Day 4, a slow yurt evening on Day 2, a free afternoon in Bishkek on Day 5.', ru_p: 'Не «бонусный треккинг». Настоящая пауза — горячие источники на 4-й день, медленный вечер в юрте на 2-й, свободные полдня в Бишкеке на 5-й.' },
  { n: 'IV', en_h: '1.5% of each booking funds pasture repair.', ru_h: '1,5% с каждого бронирования — на пастбища.', en_p: 'We contribute to the Jaichy Union\'s overgrazing recovery program in the Suusamyr and Arpa valleys. It\'s small. It\'s consistent.', ru_p: 'Мы поддерживаем программу восстановления пастбищ в долинах Суусамыр и Арпа.' },
];

export const ARTICLES = [
  {
    kicker_en: 'Field note · 5 min read',
    kicker_ru: 'Заметка · 5 мин',
    h_en: 'Why we built the All Colors loop around Issyk-Kul',
    h_ru: 'Почему маршрут «Все краски» построен вокруг Иссык-Куля',
    by_en: 'By Galya · Spring 2026',
    by_ru: 'Галя · Весна 2026',
    p_en: 'Six days is the sweet spot between a flyover and a long expedition. We pace the lake so each day belongs to one thing — Burana, then canyon, then horses, then water.',
    p_ru: 'Шесть дней — золотая середина между «галопом» и долгой экспедицией. Каждый день — про одно: сначала Бурана, потом каньон, потом кони, потом вода.',
    photo_url: 'https://resize.tripster.ru/eOuLMgEiJ27KEnoj6FOcNJtqbbI=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/01cf38f3-6650-42a4-afa8-038d494c9ad3.jpg',
    photo: 'PHOTO — Issyk-Kul shore, late afternoon',
  },
  {
    kicker_en: 'Tradition · 4 min read',
    kicker_ru: 'Традиция · 4 мин',
    h_en: 'The berkutchi: a working bond, not a show',
    h_ru: 'Беркутчи: не шоу, а рабочая связь',
    by_en: 'By the Bokonbaevo team',
    by_ru: 'Команда в Боконбаево',
    p_en: 'The eagle comes back to the glove because the hunter kept his word — fed her, walked her, never broke routine. The demo on Day 2 isn\'t staged. The bond is real.',
    p_ru: 'Беркут возвращается на руку, потому что охотник держит слово — кормит, выгуливает, не нарушает ритм. Демонстрация на второй день — не постановка. Связь настоящая.',
    photo_url: 'https://resize.tripster.ru/BSJpQUJS1sbqw1a21HZE9_PCCbo=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/e300c9b9-9914-4e76-8c81-b2560188a51b.jpg',
    photo: 'PHOTO — Berkutchi at golden hour',
  },
  {
    kicker_en: 'Craft · 3 min read',
    kicker_ru: 'Ремесло · 3 мин',
    h_en: 'What you actually make at the Day 5 felt masterclass',
    h_ru: 'Что вы действительно делаете на мастер-классе по войлоку',
    by_en: 'By the kitchen, Kochkor',
    by_ru: 'Кухня в Кочкоре',
    p_en: 'Merino wool, hot water, a bamboo mat and your hands. By the end of the session you walk out with a small shyrdak square — not a souvenir from a shop, a thing you made.',
    p_ru: 'Шерсть мериноса, горячая вода, бамбуковый коврик и ваши руки. К концу занятия в руках — небольшой шырдак, не сувенир из лавки, а вещь, которую вы сделали сами.',
    photo_url: 'https://resize.tripster.ru/9F-WxIl9-58Oe_pcDL0TuINCzOU=/fit-in/1000x1350/filters:no_upscale()/https://cdn.tripster.ru/photos/bd886e89-4c57-4418-aa8a-f7078f04da84.jpg',
    photo: 'PHOTO — Felt patterns on the loom',
  },
];
